Our goal is to make P2PNet one of the top tier go-to NuGet libraries for peer-to-peer network applications in the .Net ecosystem. This includes a mixture of good working code, good documentation, and dedication.
At some point in the future once the P2PNet library is matured and has an official stable release, we would like to publish a Wiki page on a dedicated domain. If you do consider a donation, 100% of all proceeds
will be set aside for creating an official space for P2PNet with a developer Wiki and possibly even a public forum.

You are free to use P2PNet to your liking, but do consider a donation.

custom: ['https://www.paypal.me/cdebon']
