# fly.toml app configuration file generated for p2pnet on 2025-02-17T22:08:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[build]
image = "ghcr.io/realchrisdebon/p2pnet/p2pbootstrap:latest"

app = 'p2pnet'
primary_region = 'dfw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
